require("coderxin.core.options")
require("coderxin.core.keymap")

require("coderxin.plugins-setup")

require("coderxin.plugins.lsp")
require("coderxin.plugins.treesitter")
require("coderxin.plugins.telescope")
require("coderxin.plugins.nvim-tree")
require("coderxin.plugins.autopairs")
require("coderxin.plugins.fidget")
require("coderxin.plugins.blankline")
require("coderxin.plugins.todo-comments")
require("coderxin.plugins.lualine")
require("coderxin.plugins.rust-tools")
require("coderxin.plugins.comment")
